#include "nuttx/config.h"

#ifdef CONFIG_BSP_USING_UART1
#define BSP_USING_UART1
#ifdef CONFIG_BSP_UART1_RX_USING_DMA
#define BSP_UART1_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART1_TX_USING_DMA
#define BSP_UART1_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART2
#define BSP_USING_UART2
#ifdef CONFIG_BSP_UART2_RX_USING_DMA
#define BSP_UART2_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART2_TX_USING_DMA
#define BSP_UART2_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART3
#define BSP_USING_UART3
#ifdef CONFIG_BSP_UART3_RX_USING_DMA
#define BSP_UART3_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART3_TX_USING_DMA
#define BSP_UART3_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART4
#define BSP_USING_UART4
#ifdef CONFIG_BSP_UART4_RX_USING_DMA
#define BSP_UART4_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART4_TX_USING_DMA
#define BSP_UART4_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART5
#define BSP_USING_UART5
#ifdef CONFIG_BSP_UART5_RX_USING_DMA
#define BSP_UART5_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART5_TX_USING_DMA
#define BSP_UART5_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART6
#define BSP_USING_UART6
#ifdef CONFIG_BSP_UART6_RX_USING_DMA
#define BSP_UART6_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART6_TX_USING_DMA
#define BSP_UART6_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_LPUART1
#define BSP_USING_LPUART1
#ifdef CONFIG_BSP_LPUART1_RX_USING_DMA
#define BSP_LPUART1_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_LPUART1_TX_USING_DMA
#define BSP_LPUART1_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_I2C
#define BSP_USING_I2C CONFIG_BSP_USING_I2C
#endif 
#ifdef CONFIG_BSP_USING_I2C1
#define BSP_USING_I2C1 	CONFIG_BSP_USING_I2C1
#endif
#ifdef CONFIG_BSP_USING_I2C2 
#define BSP_USING_I2C2	CONFIG_BSP_USING_I2C2
#endif
#ifdef CONFIG_BSP_USING_I2C3
#define BSP_USING_I2C3 CONFIG_BSP_USING_I2C3
#endif
#ifdef CONFIG_BSP_USING_I2C4
#define BSP_USING_I2C4 CONFIG_BSP_USING_I2C4
#endif
#ifdef CONFIG_BSP_USING_I2C5
#define BSP_USING_I2C5 CONFIG_BSP_USING_I2C5
#endif
#ifdef CONFIG_BSP_USING_I2C6
#define BSP_USING_I2C6 CONFIG_BSP_USING_I2C6
#endif
#ifdef CONFIG_BSP_USING_I2C7
#define BSP_USING_I2C7 CONFIG_BSP_USING_I2C7
#endif

#ifdef CONFIG_BSP_I2C1_USING_DMA
#define BSP_I2C1_USING_DMA CONFIG_BSP_I2C1_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C2_USING_DMA
#define BSP_I2C2_USING_DMA CONFIG_BSP_I2C2_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C3_USING_DMA
#define BSP_I2C3_USING_DMA CONFIG_BSP_I2C3_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C4_USING_DMA
#define BSP_I2C4_USING_DMA CONFIG_BSP_I2C4_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C5_USING_DMA
#define BSP_I2C5_USING_DMA CONFIG_BSP_I2C5_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C6_USING_DMA
#define BSP_I2C6_USING_DMA CONFIG_BSP_I2C6_USING_DMA
#endif
#ifdef CONFIG_BSP_I2C7_USING_DMA
#define BSP_I2C7_USING_DMA CONFIG_BSP_I2C7_USING_DMA
#endif

#ifdef CONFIG_BSP_USING_SPI
#define BSP_USING_SPI CONFIG_BSP_USING_SPI
#endif
#ifdef CONFIG_BSP_USING_SPI1
#define BSP_USING_SPI1 CONFIG_BSP_USING_SPI1
#endif
#ifdef CONFIG_BSP_USING_SPI2
#define BSP_USING_SPI2 CONFIG_BSP_USING_SPI2
#endif

#ifdef CONFIG_BSP_SPI1_TX_USING_DMA
#define BSP_SPI1_TX_USING_DMA CONFIG_BSP_SPI1_TX_USING_DMA
#endif
#ifdef CONFIG_BSP_SPI1_RX_USING_DMA
#define BSP_SPI1_RX_USING_DMA CONFIG_BSP_SPI1_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_SPI2_TX_USING_DMA
#define BSP_SPI2_TX_USING_DMA CONFIG_BSP_SPI2_TX_USING_DMA
#endif
#ifdef CONFIG_BSP_SPI2_RX_USING_DMA
#define BSP_SPI2_RX_USING_DMA CONFIG_BSP_SPI2_RX_USING_DMA
#endif

/* ADC mappings */
#ifdef CONFIG_BSP_USING_ADC
#define BSP_USING_ADC
#endif
#ifdef CONFIG_BSP_USING_ADC1
#define BSP_USING_ADC1
#endif
#ifdef CONFIG_BSP_ADC1_USING_DMA
#define BSP_ADC1_USING_DMA
#endif
#ifdef CONFIG_BSP_USING_ADC2
#define BSP_USING_ADC2
#endif

/* Timer mappings */
#ifdef CONFIG_BSP_USING_TIM
#define BSP_USING_TIM
#endif
#ifdef CONFIG_BSP_USING_GPTIM1
#define BSP_USING_GPTIM1
#endif
#ifdef CONFIG_BSP_USING_GPTIM2
#define BSP_USING_GPTIM2
#endif
#ifdef CONFIG_BSP_USING_GPTIM3
#define BSP_USING_GPTIM3
#endif
#ifdef CONFIG_BSP_USING_GPTIM4
#define BSP_USING_GPTIM4
#endif
#ifdef CONFIG_BSP_USING_GPTIM5
#define BSP_USING_GPTIM5
#endif
#ifdef CONFIG_BSP_USING_ATIM1
#define BSP_USING_ATIM1
#endif
#ifdef CONFIG_BSP_USING_ATIM2
#define BSP_USING_ATIM2
#endif
#ifdef CONFIG_BSP_USING_BTIM1
#define BSP_USING_BTIM1
#endif
#ifdef CONFIG_BSP_USING_BTIM2
#define BSP_USING_BTIM2
#endif
#ifdef CONFIG_BSP_USING_BTIM3
#define BSP_USING_BTIM3
#endif
#ifdef CONFIG_BSP_USING_BTIM4
#define BSP_USING_BTIM4
#endif
#ifdef CONFIG_BSP_USING_LPTIM1
#define BSP_USING_LPTIM1
#endif
#ifdef CONFIG_BSP_USING_LPTIM2
#define BSP_USING_LPTIM2
#endif
#ifdef CONFIG_BSP_USING_LPTIM3
#define BSP_USING_LPTIM3
#endif

/* PWM mappings */
#ifdef CONFIG_BSP_USING_PWM
#define BSP_USING_PWM
#endif
#ifdef CONFIG_BSP_USING_PWM2
#define BSP_USING_PWM2 CONFIG_BSP_USING_PWM2
#endif
#ifdef CONFIG_BSP_USING_PWM3
#define BSP_USING_PWM3 CONFIG_BSP_USING_PWM3
#endif
#ifdef CONFIG_BSP_USING_PWM4
#define BSP_USING_PWM4 CONFIG_BSP_USING_PWM4
#endif
#ifdef CONFIG_BSP_USING_PWM5
#define BSP_USING_PWM5 CONFIG_BSP_USING_PWM5
#endif
#ifdef CONFIG_BSP_USING_PWM6
#define BSP_USING_PWM6 CONFIG_BSP_USING_PWM6
#endif
#ifdef CONFIG_BSP_USING_PWMA1
#define BSP_USING_PWMA1 CONFIG_BSP_USING_PWMA1
#endif
#ifdef CONFIG_BSP_USING_PWMA2
#define BSP_USING_PWMA2 CONFIG_BSP_USING_PWMA2
#endif

/* MPI2 mappings */
#ifdef CONFIG_BSP_ENABLE_MPI2
#define BSP_ENABLE_MPI2
#endif
#ifdef CONFIG_BSP_MPI2_MODE
#define BSP_MPI2_MODE CONFIG_BSP_MPI2_MODE
#endif
#ifdef CONFIG_BSP_MPI2_NOR
#define BSP_MPI2_NOR
#endif
#ifdef CONFIG_BSP_MPI2_MEM_SIZE
#define BSP_MPI2_MEM_SIZE CONFIG_BSP_MPI2_MEM_SIZE
#endif

/* USB mappings */
#ifdef CONFIG_SF32LB52_USBDEV
#define BSP_USING_USBD
#endif

#ifdef CONFIG_BSP_USING_LCDC
#define BSP_USING_LCDC
#endif

#ifdef CONFIG_SIFLI_LCD
#define BSP_USING_LCD
#endif

#ifdef CONFIG_LCD_USING_CO5300
#define LCD_USING_CO5300
#endif

#ifdef CONFIG_BSP_LCDC_USING_QADSPI
#define BSP_LCDC_USING_QADSPI
#endif

#ifdef CONFIG_LCD_CO5300_VSYNC_ENABLE
#define LCD_CO5300_VSYNC_ENABLE
#endif

#ifdef CONFIG_BSP_USING_PSRAM
#define BSP_USING_PSRAM
#endif

#ifdef CONFIG_BSP_USING_PSRAM1
#define BSP_USING_PSRAM1
#endif

#ifdef CONFIG_BSP_QSPI1_MODE
#define BSP_QSPI1_MODE CONFIG_BSP_QSPI1_MODE
#endif

#ifdef CONFIG_BSP_QSPI1_MEM_SIZE
#define BSP_QSPI1_MEM_SIZE CONFIG_BSP_QSPI1_MEM_SIZE
#endif

#ifndef NX_IRQ
#define NX_IRQ(irqn) ((irqn) + 16)
#endif


